development:
  adapter: postgresql
  database: boombotix_development
  host: localhost

test:
  adapter: postgresql
  database: boombotix_test
  host: localhost

staging:
  adapter: postgresql
  database: boombotix
  host: localhost
